-- Safe property replacement script that preserves favorites
-- Generated on: 2025-08-26T13:37:15.952626

BEGIN;

-- Create backup table
CREATE TABLE IF NOT EXISTS "PropertiesBackup" AS SELECT * FROM "Properties";

-- Remove all favorite relationships first (they'll be reset)
DELETE FROM "FavoriteProperties";

-- Clear existing properties 
DELETE FROM "Properties";

-- Reset sequence
ALTER SEQUENCE "Properties_Id_seq" RESTART WITH 1;

-- Insert new properties (truncated for brevity - will be generated by script)
INSERT INTO "Properties" ("Address", "City", "State", "ZipCode", "Price", "Bedrooms", "Bathrooms", "SquareFeet", "PropertyType", "Description", "ImageUrl", "ListedDate", "IsActive") VALUES 
('1984 Willow Brook Way', 'San Antonio', 'TX', '78279', 305000, 2, 2, 1351, 'Single Family', 'Spacious single family offering comfort and convenience in prime San Antonio location.', 'https://images.unsplash.com/gKXKBY-C-Dk', NOW(), true),
('8234 Harbor Point Ln', 'Portland', 'OR', '97252', 620000, 3, 2, 1544, 'Single Family', 'Well-maintained single family with hardwood floors and updated fixtures throughout.', 'https://images.unsplash.com/dBQQyDRWVAE', NOW(), true);

COMMIT;

-- Verify data
SELECT COUNT(*) as "New Property Count" FROM "Properties";
SELECT "City", COUNT(*) as "Count" FROM "Properties" GROUP BY "City" ORDER BY "Count" DESC;